In [22]:
# generate winner for each grand slam from 2000 onwards
import pandas as pd

df = pd.read_csv("../tennis_atp-master/atp_matches_2000.csv")

# Extract year
df["year"] = df["tourney_date"].astype(str).str[:4].astype(int)


grand_slams = [
    "Australian Open",
    "Roland Garros",
    "Wimbledon",
    "US Open"
]

# Keep only Grand Slam finals
gs_finals = df[(df["tourney_name"].isin(grand_slams)) & (df["round"] == "F")]

# Get winner of each grand slam each year
winners1 = gs_finals[["year", "tourney_name", "winner_name"]].sort_values(["year", "tourney_name"])

print(winners1)

      year     tourney_name      winner_name
2699  2000  Australian Open     Andre Agassi
2256  2000    Roland Garros  Gustavo Kuerten
2510  2000          US Open      Marat Safin
2383  2000        Wimbledon     Pete Sampras

In [25]:
df = pd.read_csv("../tennis_atp-master/atp_matches_2001.csv")

# Extract year
df["year"] = df["tourney_date"].astype(str).str[:4].astype(int)


grand_slams = [
    "Australian Open",
    "Roland Garros",
    "Wimbledon",
    "US Open"
]

# Keep only Grand Slam finals
gs_finals = df[(df["tourney_name"].isin(grand_slams)) & (df["round"] == "F")]

# Get winner of each grand slam each year
winners2 = gs_finals[["year", "tourney_name", "winner_name"]].sort_values(["year", "tourney_name"])

print(winners2)
ans = pd.concat([winners1, winners2])
ans

      year     tourney_name       winner_name
2730  2001  Australian Open      Andre Agassi
2256  2001    Roland Garros   Gustavo Kuerten
2541  2001          US Open    Lleyton Hewitt
2414  2001        Wimbledon  Goran Ivanisevic

      year     tourney_name       winner_name
2699  2000  Australian Open      Andre Agassi
2256  2000    Roland Garros   Gustavo Kuerten
2510  2000          US Open       Marat Safin
2383  2000        Wimbledon      Pete Sampras
2730  2001  Australian Open      Andre Agassi
2256  2001    Roland Garros   Gustavo Kuerten
2541  2001          US Open    Lleyton Hewitt
2414  2001        Wimbledon  Goran Ivanisevic

In [ ]:

ans = []
for i in range(2000, 2025):
    df = pd.read_csv(f"../tennis_atp-master/atp_matches_{i}.csv")
    
    # Extract year
    df["year"] = df["tourney_date"].astype(str).str[:4].astype(int)


    grand_slams = [
        "Australian Open",
        "Roland Garros",
        "Wimbledon",
        "US Open"
    ]

    # Keep only Grand Slam finals
    gs_finals = df[(df["tourney_name"].isin(grand_slams)) & (df["round"] == "F")]

    # Get winner of each grand slam each year
    winners = gs_finals[["year", "tourney_name", "winner_name"]].sort_values(["year", "tourney_name"])
    ans.append(winners)
ans = pd.concat(ans)
ans

      year     tourney_name      winner_name
2699  2000  Australian Open     Andre Agassi
2256  2000    Roland Garros  Gustavo Kuerten
2510  2000          US Open      Marat Safin
2383  2000        Wimbledon     Pete Sampras
2730  2001  Australian Open     Andre Agassi
...    ...              ...              ...
1424  2023    Roland Garros   Novak Djokovic
1721  2023        Wimbledon   Carlos Alcaraz
263   2024  Australian Open    Jannik Sinner
1302  2024    Roland Garros   Carlos Alcaraz
1725  2024        Wimbledon   Carlos Alcaraz

[94 rows x 3 columns]

In [28]:
# rows will be year, column will be tourney name, value will be winner
table = ans.pivot(index="year", columns="tourney_name", values="winner_name")

print(table)

tourney_name   Australian Open        Roland Garros                US Open  \
year
2000              Andre Agassi      Gustavo Kuerten            Marat Safin
2001              Andre Agassi      Gustavo Kuerten         Lleyton Hewitt
2002          Thomas Johansson         Albert Costa           Pete Sampras
2003              Andre Agassi  Juan Carlos Ferrero           Andy Roddick
2004             Roger Federer        Gaston Gaudio          Roger Federer
2005               Marat Safin         Rafael Nadal          Roger Federer
2006             Roger Federer         Rafael Nadal          Roger Federer
2007             Roger Federer         Rafael Nadal          Roger Federer
2008            Novak Djokovic         Rafael Nadal          Roger Federer
2009              Rafael Nadal        Roger Federer  Juan Martin del Potro
2010             Roger Federer         Rafael Nadal           Rafael Nadal
2011            Novak Djokovic         Rafael Nadal         Novak Djokovic
2012            Novak Djokovic         Rafael Nadal            Andy Murray
2013            Novak Djokovic         Rafael Nadal           Rafael Nadal
2014             Stan Wawrinka         Rafael Nadal            Marin Cilic
2015            Novak Djokovic        Stan Wawrinka         Novak Djokovic
2016            Novak Djokovic       Novak Djokovic          Stan Wawrinka
2017             Roger Federer         Rafael Nadal           Rafael Nadal
2018             Roger Federer         Rafael Nadal         Novak Djokovic
2019            Novak Djokovic         Rafael Nadal           Rafael Nadal
2020            Novak Djokovic         Rafael Nadal                    NaN
2021            Novak Djokovic       Novak Djokovic                    NaN
2022              Rafael Nadal         Rafael Nadal                    NaN
2023            Novak Djokovic       Novak Djokovic                    NaN
2024             Jannik Sinner       Carlos Alcaraz                    NaN

tourney_name         Wimbledon
year
2000              Pete Sampras
2001          Goran Ivanisevic
2002            Lleyton Hewitt
2003             Roger Federer
2004             Roger Federer
2005             Roger Federer
2006             Roger Federer
2007             Roger Federer
2008              Rafael Nadal
2009             Roger Federer
2010              Rafael Nadal
2011            Novak Djokovic
2012             Roger Federer
2013               Andy Murray
2014            Novak Djokovic
2015            Novak Djokovic
2016               Andy Murray
2017             Roger Federer
2018            Novak Djokovic
2019            Novak Djokovic
2020                       NaN
2021            Novak Djokovic
2022            Novak Djokovic
2023            Carlos Alcaraz
2024            Carlos Alcaraz

In [35]:
ans = []
for i in range(2000, 2025):
    df = pd.read_csv(f"../tennis_atp-master/atp_matches_{i}.csv")
    
    # Extract year
    df["year"] = df["tourney_date"].astype(str).str[:4].astype(int)


    grand_slams = [
        "Australian Open",
        "Roland Garros",
        "Wimbledon",
        "US Open"
    ]

    # Keep only Grand Slam finals
    gs_finals = df[(df["tourney_name"].isin(grand_slams)) & (df["round"] == "F")]

    # Get winner of each grand slam each year
    winners = gs_finals[["year", "tourney_name", "winner_name", "winner_age"]].sort_values(["year", "tourney_name"])
    ans.append(winners)
ans = pd.concat(ans)
a = ans.loc[ans["winner_age"].idxmin()]
a

year                     2005
tourney_name    Roland Garros
winner_name      Rafael Nadal
winner_age               18.9
Name: 2202, dtype: object